apiVersion: v1
kind: Service
metadata:
  name: mss-frontend
spec:
  selector:
    app: mss-frontend
  ports:
  - port: 3000
    targetPort: 3000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: mss-api
spec:
  selector:
    app: mss-api
  ports:
  - port: 3001
    targetPort: 3001
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: mss-postgres
spec:
  selector:
    app: mss-postgres
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: mss-redis
spec:
  selector:
    app: mss-redis
  ports:
  - port: 6379
    targetPort: 6379
  type: ClusterIP