global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'mss-platform'

rule_files:
  - "alerts.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  # Docker containers via cAdvisor
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # MSS Frontend application
  - job_name: 'mss-frontend'
    static_configs:
      - targets: ['mss-frontend:3000']
    metrics_path: '/api/metrics'

  # MSS Backend API
  - job_name: 'mss-api'
    static_configs:
      - targets: ['mss-api:3001']
    metrics_path: '/api/metrics'

  # PostgreSQL via postgres_exporter
  - job_name: 'postgresql'
    static_configs:
      - targets: ['postgres-exporter:9187']

  # Redis via redis_exporter
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']