name: Simple CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Install and test Frontend
        working-directory: ./apps/frontend
        run: |
          echo "Installing frontend dependencies..."
          npm ci || npm install
          echo "Frontend installed successfully"
      
      - name: Install and test API
        working-directory: ./apps/api
        run: |
          echo "Installing API dependencies..."
          npm ci || npm install
          echo "API installed successfully"
      
      - name: Success
        run: echo "✅ CI passed! Dependencies installed successfully."